# Set base URL for site - should end with a trailing slash
baseUrl = "http://melaniecebula.github.io/"

title = "Melanie Cebula's Blog"
theme = "slick"

languageCode = "en"
defaultContentLanguage = "en-us"

# Will appear below the footer links with a © sign and the current year
copyright = "Melanie Cebula — All rights reserved."


pygmentsCodefences = true               # Enable highlighting inside codefences
pygmentsCodeFencesGuessSyntax = true    # Highlight code without language tag
pygmentsUseClasses = true               # Use external style sheet
pygmentsUseClassic = false              # Force use of chroma

canonifyURLs = true

# Configure pagination
Paginate = 10
PaginatePath = "page"

[params]
    # Site description
    description = "Melanie Cebula's blog"

    # Favicon file (relative to baseURL)
    favicon = "img/favicon.png"

    # Enables custom date format (optional, the default is MM-DD-YYYY)
    # For reference to date and time templating, see:
    # https://gohugo.io/functions/format/#hugo-date-and-time-templating-reference
    datefmt = "Mon, 02 Jan 2006 15:04:05 MST"

    # Decide if only summaries are shown on the main page or the full content
    showfullcontent = true

    # Uses Hugo internal templates if set
    opengraph = false
    schema = false
    twitter_cards = false


# Define all supported taxonomies (add series to the default)
[taxonomies]
    tags = "tags"
    categories = "categories"
    series = "series"


[author]
    name = "Melanie Cebula"
    email = "melaniecebula.bass@gmail.com"


[menu]

    # Configure main menu entries (header)
    # Currently set to list all taxonomies and posts
    [[menu.main]]
        identifier = "post"
        name = "Posts"
        url = "/posts/"
        weight = 1

    # Add some footer links to your likings
    [[menu.footer]]
        name = "GitHub"
        url = "https://github.com/melaniecebula"
        weight = 1

    [[menu.footer]]
        name = "Twitter"
        url = "https://twitter.com/melaniecebula"
        weight = 2
